### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by pablote** [lubritto/flutter_share#1]
I tried to test out your pluging today, and I get this error, only by adding the dependency it's already triggered:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.android.support:appcompat-v7' has different version for the compile (27.1.0) and runtime (27.1.1) classpath. You should manually set the same version via DependencyResolution
```

**Comment by lubritto** [comment]
Try to adding
implementation 'com.android.support:appcompat-v7:27.1.1 and implementation 'com.android.support:support-v4:27.1.1 to the build.gradle file

**Comment by pablote** [comment]
Ok, that worked. Now I'm getting this error the moment I call share, without further info:

```
I/        (12913): FlutterShare: Error`
```

My failling line looks like this: 
```
FlutterShare.share(fileUrl: file.uri.toString(), title: 'Share');
```

**Comment by lubritto** [comment]
Sorry about that, I need update the description.. This plugin needs storage permission but i didn't implemented yet, did you set this permission ?

**Comment by lubritto** [comment]
Closed for now, if persists open other issue.
