### ISSUE TITLE
ipad not supported

### ISSUE THREAD

**Issue by calvino80** [lubritto/flutter_share#8]
flutter share causes ipad devices to close host app without any error messages. I tested on ipad mini 2 Model MF075LL/A with iOS 12.4.4 and ipad Model MP2H2LL/A with iOS 13.3.

**Comment by izzabellerina** [comment]
me too , I try running with Xcode and then it throw error : Thread 1: Exception: "UIPopoverPresentationController (<UIPopoverPresentationController: 0x15948f9e0>) should have a non-nil sourceView or barButtonItem set before the presentation occurs." 

and this code which Xcode want me to fix something but I don't know what to do.

#import <Flutter/Flutter.h>
#import <UIKit/UIKit.h>
#import "AppDelegate.h"

int main(int argc, char* argv[]) {
  @autoreleasepool {
      
      
    return UIApplicationMain(argc, argv, nil, NSStringFromClass([AppDelegate class]));
  }
}
 


thank a lot.

**Comment by karmazinkd** [comment]
Same thing here:
Simulator iPad Pro (3-gen). 
iOS 13.3.1
app crashes with the message:

*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48
	2   UIKitCore                           0x00007fff4791b9a1 __66-[UIPopoverPresentationController presentationTransitionWillBegin]_block_invoke + 0
	3   UIKitCore                           0x00007fff479266be __71-[UIPresentationController _initViewHierarchyForPresentationSuperview:]_block_invoke + 2604
	4   UIKitCore                           0x00007fff47923f10 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke.465 + 536
	5   UIKitCore                           0x00007fff4809be5b _runAfterCACommitDeferredBlocks + 352
	6   UIKitCore   <…>
Application finished.

**Comment by calvino80** [comment]
Hi Lubritto,
    the swift code for the share it plugin, line 47-55 creates
a UIPopoverPresentationController which may be required to make this
flutter share work on iPad devices:

https://gitlab.com/illescasDaniel-Flutter/OpenSource/shareit/-/blob/master/ios/Classes/SwiftShareItPlugin.swift

https://www.howtobuildsoftware.com/index.php/how-do/Qfc/ios-ipad-swift-uipopovercontroller-uiactivityviewcontroller-uiactivity-activityviewcontroller-crash-on-ipad-in-swift


Mike

**Comment by claptimes5** [comment]
@calvino80 I used the code you referenced and made a patch for iPads. If someone has a better way of fixing, please do! I'm not that familiar with the code.

**Comment by neokree** [comment]
@claptimes5 ok I think that we have done the same thing here. 

In my pull request I have also added some commit for migrating to the latest flutter version (in stable channel) and also fixed either for `share` and `shareFile`.  I think it is best if we agree on one pull request, so that @calvino80 can simply review it.

Could you please check my pull request? #11 
Thanks

**Comment by claptimes5** [comment]
@neokree are you asking me to review it? I think it makes more sense for the repo maintainer to review your PR... That being said, I think it would be much easier to review/merge if the PR only contains the change necessary to fix the issue. I'd remove the rest of the commits.

**Comment by neokree** [comment]
@claptimes5,  no I don't want you to review it, I was trying to make the things easier to @calvino80 agreeing on one pull request over the other. 

Anyway, let's wait for his response

**Comment by neokree** [comment]
I have realized now that calvino80 is not the repo owner. 
In my previous messages I was referring to @lubritto.

**Comment by lubritto** [comment]
Can you check if the error is solved on the master?

**Comment by neokree** [comment]
The fix works only if the `shareFile` method is used. 
If the `share` method is used, then the app still crashes on iPad.

**Comment by neokree** [comment]
@lubritto could you please review the new pull request?

**Comment by herrmayr** [comment]
Does the new version work for you?
The above mentioned error doesn't occur anymore, but visually, nothing happens when called shareFile, and the console logs:
```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: 
#0      FlutterShare.shareFile (package:flutter_share/flutter_share.dart:56)
#1      _ScreenVideoState.shareFileAction (package:mediaconverter/screen_video.dart:82)
#2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706)
#3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182)
#5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486)
#6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282)
#7      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199)
#8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467)
#9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76)
#10     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117)
#11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379)
#12     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115)
#13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101)
#14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218)
#15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198)
#16     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156)
#17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102)
#18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86)
#19     _rootRunUnary (dart:async/zone.dart:1138)
#20     _CustomZone.runUnary (dart:async/zone.dart:1031)
#21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#22     _invoke1 (dart:ui/hooks.dart:273)
#23     _dispatchPointerDataPacket (dart:ui/hooks.dart:182)
```
Does anyone else have the same issue?

**Comment by neokree** [comment]
@herrmayr from what I know, the fix for shareFile was only merged on master, it is not released on pub.dev yet

**Comment by neokree** [comment]
@lubritto Could you please check out my pull request? Thanks

**Comment by xiyulangzi** [comment]
with iOS 14.0.1 the same error still happening

**Comment by lubritto** [comment]
Fixed guys!
